### ISSUE TITLE
Run ./installPrerequisites.sh - Could not build Bazel

### ISSUE THREAD

**Issue by shuyu0815** [jetsonhacks/installTensorFlowTX1#23]
Anyone got this error when run the installPrerequisites.sh ?

ERROR: /home/ubuntu/bazel-0.5.2-dist/src/tools/android/java/com/google/devtools/build/android/ziputils/BUILD:20:1: Building src/tools/android/java/com/google/devtools/build/android/ziputils/libziputils_lib.jar (12 source files) failed: Worker process sent response with exit code: 1.
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
	at com.sun.tools.javac.util.Log.localize(Log.java:788)
	at com.sun.tools.javac.util.Log.printLines(Log.java:586)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:170)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:103)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:106)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:53)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:109)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:121)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:89)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:66)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
	... 15 more
Target //src:bazel failed to build
INFO: Elapsed time: 702.070s, Critical Path: 119.12s

ERROR: Could not build Bazel

Can you give me how to fix it or some suggestions ?
Thanks you very much !

**Comment by shuyu0815** [comment]
It should install with lower jdk !

**Comment by shuyu0815** [comment]
It should install with lower jdk !
