### ISSUE TITLE
Target //tensorflow/tools/pip_package:build_pip_package failed to build

### ISSUE THREAD

**Issue by LimSM** [jetsonhacks/installTensorFlowTX1#5]
when i was built, i receive below message.
It said Build reported as successful, I can't progress
How to resolve it?

`Target //tensorflow/tools/pip_package:build_pip_package failed to build
Unhandled exception thrown during build; message: Build reported as successful but not all artifacts and targets built: EvaluationResult{catastrophe=null, errorMap={}, resultMap={ARTIFACT:stable-status.txt com.google.devtools.build.lib.skyframe.WorkspaceStatusValue$BuildInfoKey@3f5f147a=RegularFileArtifactValue{digest=[-1, -123, -2, 45, -102, 110, 58, 68, -3, 81, 60, 49, 12, 48, -68, 38], size=60}, ARTIFACT:volatile-status.txt com.google.devtools.build.lib.skyframe.WorkspaceStatusValue$BuildInfoKey@3f5f147a=RegularFileArtifactValue{digest=[-19, -75, 71, 47, 114, 84, -9, 63, -48, -113, 103, -76, 81, 19, 92, 78], size=29}}}, [Artifact:[[/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow]bazel-out]volatile-status.txt, Artifact:[[/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow]bazel-out]stable-status.txt]
INFO: Elapsed time: 13558.497s, Critical Path: 12955.78s
java.lang.IllegalStateException: Build reported as successful but not all artifacts and targets built: EvaluationResult{catastrophe=null, errorMap={}, resultMap={ARTIFACT:stable-status.txt com.google.devtools.build.lib.skyframe.WorkspaceStatusValue$BuildInfoKey@3f5f147a=RegularFileArtifactValue{digest=[-1, -123, -2, 45, -102, 110, 58, 68, -3, 81, 60, 49, 12, 48, -68, 38], size=60}, ARTIFACT:volatile-status.txt com.google.devtools.build.lib.skyframe.WorkspaceStatusValue$BuildInfoKey@3f5f147a=RegularFileArtifactValue{digest=[-19, -75, 71, 47, 114, 84, -9, 63, -48, -113, 103, -76, 81, 19, 92, 78], size=29}}}, [Artifact:[[/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow]bazel-out]volatile-status.txt, Artifact:[[/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow]bazel-out]stable-status.txt]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:238)
	at com.google.devtools.build.lib.buildtool.SkyframeBuilder.buildArtifacts(SkyframeBuilder.java:156)
	at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:433)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:196)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:332)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:499)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:327)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:655)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1400(GrpcServerImpl.java:99)
	at com.google.devtools.build.lib.server.GrpcServerImpl$3$1.run(GrpcServerImpl.java:722)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: Build reported as successful but not all artifacts and targets built: EvaluationResult{catastrophe=null, errorMap={}, resultMap={ARTIFACT:stable-status.txt com.google.devtools.build.lib.skyframe.WorkspaceStatusValue$BuildInfoKey@3f5f147a=RegularFileArtifactValue{digest=[-1, -123, -2, 45, -102, 110, 58, 68, -3, 81, 60, 49, 12, 48, -68, 38], size=60}, ARTIFACT:volatile-status.txt com.google.devtools.build.lib.skyframe.WorkspaceStatusValue$BuildInfoKey@3f5f147a=RegularFileArtifactValue{digest=[-19, -75, 71, 47, 114, 84, -9, 63, -48, -113, 103, -76, 81, 19, 92, 78], size=29}}}, [Artifact:[[/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow]bazel-out]volatile-status.txt, Artifact:[[/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow]bazel-out]stable-status.txt]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:238)
	at com.google.devtools.build.lib.buildtool.SkyframeBuilder.buildArtifacts(SkyframeBuilder.java:156)
	at com.google.devtools.build.lib.buildtool.ExecutionTool.executeBuild(ExecutionTool.java:433)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:196)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:332)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:69)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:499)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:327)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:655)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1400(GrpcServerImpl.java:99)
	at com.google.devtools.build.lib.server.GrpcServerImpl$3$1.run(GrpcServerImpl.java:722)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by jetsonhacks** [comment]
It appears as if the Bazel system did not successfully build the entire project. Unfortunately there is an issue with incremental compilation which will not allow you to just do 'buildTensorFlow.sh' afterwards without rebuilding the entire system.

The easiest way to fix this is to upgrade the installTensorFlowTX1 repository, which will install a patch to fix the Bazel incremental compilation. Unfortunately this requires that the directory tensorflow be deleted and cloned again. You should not have to reinstall prerequisites again.

An alternative is to run the correct patches to fix the Bazel issue and the  zlib relocation issue manually, but that will require deconstructing the shell script to get the correct patches and require some knowledge about what it is trying to accomplish.

Once installed correctly, if you encounter an issue like the one stated above  you can then do another 'buildTensorFlow.sh' and it should start building where it left off.

**Comment by jetsonhacks** [comment]
This has not been commented on for some time, closing.
